//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarbarianPrince.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?><WindowPlacement xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema""><length>44</length><flags>2</flags><showCmd>3</showCmd><minPosition><X>-1</X><Y>-1</Y></minPosition><maxPosition><X>-1</X><Y>-1</Y></maxPosition><normalPosition><Left>26</Left><Top>26</Top><Right>1946</Right><Bottom>1106</Bottom></normalPosition></WindowPlacement>")]
        public string WindowPlacement {
            get {
                return ((string)(this["WindowPlacement"]));
            }
            set {
                this["WindowPlacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double ZoomCanvas {
            get {
                return ((double)(this["ZoomCanvas"]));
            }
            set {
                this["ZoomCanvas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double ScrollViewerHeight {
            get {
                return ((double)(this["ScrollViewerHeight"]));
            }
            set {
                this["ScrollViewerHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("827")]
        public double ScrollViewerWidth {
            get {
                return ((double)(this["ScrollViewerWidth"]));
            }
            set {
                this["ScrollViewerWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameDirectoryName {
            get {
                return ((string)(this["GameDirectoryName"]));
            }
            set {
                this["GameDirectoryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameRestorePoint {
            get {
                return ((string)(this["GameRestorePoint"]));
            }
            set {
                this["GameRestorePoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?><ArrayOfAnyType xmlns:xsi=\"http://www.w3.o" +
            "rg/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"><anyTyp" +
            "e xsi:type=\"Option\"><Name>AutoSetup</Name><IsEnabled>false</IsEnabled></anyType>" +
            "<anyType xsi:type=\"Option\"><Name>AutoWealthRollForUnderFive</Name><IsEnabled>fal" +
            "se</IsEnabled></anyType><anyType xsi:type=\"Option\"><Name>PrinceHorse</Name><IsEn" +
            "abled>false</IsEnabled></anyType><anyType xsi:type=\"Option\"><Name>PrincePegasus<" +
            "/Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Option\"><Name>Pri" +
            "nceCoin</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Option\"><" +
            "Name>PrinceFood</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"O" +
            "ption\"><Name>StartWithNerveGame</Name><IsEnabled>false</IsEnabled></anyType><any" +
            "Type xsi:type=\"Option\"><Name>StartWithNecklass</Name><IsEnabled>false</IsEnabled" +
            "></anyType><anyType xsi:type=\"Option\"><Name>RandomParty10</Name><IsEnabled>false" +
            "</IsEnabled></anyType><anyType xsi:type=\"Option\"><Name>RandomParty08</Name><IsEn" +
            "abled>false</IsEnabled></anyType><anyType xsi:type=\"Option\"><Name>RandomParty05<" +
            "/Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Option\"><Name>Ran" +
            "domParty03</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Option" +
            "\"><Name>RandomParty01</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:t" +
            "ype=\"Option\"><Name>PartyCustom</Name><IsEnabled>false</IsEnabled></anyType><anyT" +
            "ype xsi:type=\"Option\"><Name>Dwarf</Name><IsEnabled>false</IsEnabled></anyType><a" +
            "nyType xsi:type=\"Option\"><Name>Eagle</Name><IsEnabled>false</IsEnabled></anyType" +
            "><anyType xsi:type=\"Option\"><Name>Elf</Name><IsEnabled>false</IsEnabled></anyTyp" +
            "e><anyType xsi:type=\"Option\"><Name>Falcon</Name><IsEnabled>false</IsEnabled></an" +
            "yType><anyType xsi:type=\"Option\"><Name>Griffon</Name><IsEnabled>false</IsEnabled" +
            "></anyType><anyType xsi:type=\"Option\"><Name>Harpy</Name><IsEnabled>false</IsEnab" +
            "led></anyType><anyType xsi:type=\"Option\"><Name>Magician</Name><IsEnabled>false</" +
            "IsEnabled></anyType><anyType xsi:type=\"Option\"><Name>Mercenary</Name><IsEnabled>" +
            "false</IsEnabled></anyType><anyType xsi:type=\"Option\"><Name>Merchant</Name><IsEn" +
            "abled>false</IsEnabled></anyType><anyType xsi:type=\"Option\"><Name>Minstrel</Name" +
            "><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Option\"><Name>Monk</Na" +
            "me><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Option\"><Name>Porter" +
            "Slave</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Option\"><Na" +
            "me>Priest</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Option\"" +
            "><Name>TrueLove</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"O" +
            "ption\"><Name>Wizard</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:typ" +
            "e=\"Option\"><Name>PartyMounted</Name><IsEnabled>false</IsEnabled></anyType><anyTy" +
            "pe xsi:type=\"Option\"><Name>PartyAirborne</Name><IsEnabled>false</IsEnabled></any" +
            "Type><anyType xsi:type=\"Option\"><Name>RandomHex</Name><IsEnabled>false</IsEnable" +
            "d></anyType><anyType xsi:type=\"Option\"><Name>RandomTown</Name><IsEnabled>false</" +
            "IsEnabled></anyType><anyType xsi:type=\"Option\"><Name>RandomLeft</Name><IsEnabled" +
            ">false</IsEnabled></anyType><anyType xsi:type=\"Option\"><Name>RandomRight</Name><" +
            "IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Option\"><Name>RandomBott" +
            "om</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Option\"><Name>" +
            "0722</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Option\"><Nam" +
            "e>0109</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Option\"><N" +
            "ame>0206</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Option\">" +
            "<Name>0708</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Option" +
            "\"><Name>0711</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Opti" +
            "on\"><Name>1212</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Op" +
            "tion\"><Name>0323</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"" +
            "Option\"><Name>1923</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type" +
            "=\"Option\"><Name>0418</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:ty" +
            "pe=\"Option\"><Name>0410</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:" +
            "type=\"Option\"><Name>0409</Name><IsEnabled>false</IsEnabled></anyType><anyType xs" +
            "i:type=\"Option\"><Name>0406</Name><IsEnabled>false</IsEnabled></anyType><anyType " +
            "xsi:type=\"Option\"><Name>1611</Name><IsEnabled>false</IsEnabled></anyType><anyTyp" +
            "e xsi:type=\"Option\"><Name>0411</Name><IsEnabled>false</IsEnabled></anyType><anyT" +
            "ype xsi:type=\"Option\"><Name>1507</Name><IsEnabled>false</IsEnabled></anyType><an" +
            "yType xsi:type=\"Option\"><Name>1905</Name><IsEnabled>false</IsEnabled></anyType><" +
            "anyType xsi:type=\"Option\"><Name>1723</Name><IsEnabled>false</IsEnabled></anyType" +
            "><anyType xsi:type=\"Option\"><Name>LessHardMonsters</Name><IsEnabled>false</IsEna" +
            "bled></anyType><anyType xsi:type=\"Option\"><Name>EasyMonsters</Name><IsEnabled>fa" +
            "lse</IsEnabled></anyType><anyType xsi:type=\"Option\"><Name>EasiestMonsters</Name>" +
            "<IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Option\"><Name>AutoLostD" +
            "ecrease</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Option\"><" +
            "Name>ExtendEndTime</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type" +
            "=\"Option\"><Name>ReduceLodgingCosts</Name><IsEnabled>false</IsEnabled></anyType><" +
            "anyType xsi:type=\"Option\"><Name>SteadyIncome</Name><IsEnabled>false</IsEnabled><" +
            "/anyType><anyType xsi:type=\"Option\"><Name>NoLostRoll</Name><IsEnabled>false</IsE" +
            "nabled></anyType><anyType xsi:type=\"Option\"><Name>ForceNoLostEvent</Name><IsEnab" +
            "led>false</IsEnabled></anyType><anyType xsi:type=\"Option\"><Name>ForceNoEvent</Na" +
            "me><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Option\"><Name>ForceN" +
            "oRoadEvent</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Option" +
            "\"><Name>ForceNoCrossEvent</Name><IsEnabled>false</IsEnabled></anyType><anyType x" +
            "si:type=\"Option\"><Name>ForceNoRaftEvent</Name><IsEnabled>false</IsEnabled></anyT" +
            "ype><anyType xsi:type=\"Option\"><Name>ForceNoAirEvent</Name><IsEnabled>false</IsE" +
            "nabled></anyType><anyType xsi:type=\"Option\"><Name>ForceLostEvent</Name><IsEnable" +
            "d>false</IsEnabled></anyType><anyType xsi:type=\"Option\"><Name>ForceLostAfterCros" +
            "sEvent</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Option\"><N" +
            "ame>ForceEvent</Name><IsEnabled>false</IsEnabled></anyType><anyType xsi:type=\"Op" +
            "tion\"><Name>ForceCrossEvent</Name><IsEnabled>false</IsEnabled></anyType><anyType" +
            " xsi:type=\"Option\"><Name>ForceRaftEvent</Name><IsEnabled>false</IsEnabled></anyT" +
            "ype><anyType xsi:type=\"Option\"><Name>ForceAirEvent</Name><IsEnabled>false</IsEna" +
            "bled></anyType></ArrayOfAnyType>\n")]
        public string GameOptions {
            get {
                return ((string)(this["GameOptions"]));
            }
            set {
                this["GameOptions"] = value;
            }
        }
    }
}
