//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarbarianPrince.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WindowPlacement {
            get {
                return ((string)(this["WindowPlacement"]));
            }
            set {
                this["WindowPlacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double ZoomCanvas {
            get {
                return ((double)(this["ZoomCanvas"]));
            }
            set {
                this["ZoomCanvas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double ScrollViewerHeight {
            get {
                return ((double)(this["ScrollViewerHeight"]));
            }
            set {
                this["ScrollViewerHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("827")]
        public double ScrollViewerWidth {
            get {
                return ((double)(this["ScrollViewerWidth"]));
            }
            set {
                this["ScrollViewerWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameDirectoryName {
            get {
                return ((string)(this["GameDirectoryName"]));
            }
            set {
                this["GameDirectoryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameRestorePoint {
            get {
                return ((string)(this["GameRestorePoint"]));
            }
            set {
                this["GameRestorePoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"<Options>\r\n  <Option value=\"AutoSetup\">\r\n    <IsEnabled value=\"True\" />\r\n  </Opt" +
            "ion>\r\n  <Option value=\"AutoWealthRollForUnderFive\">\r\n    <IsEnabled value=\"True\"" +
            " />\r\n  </Option>\r\n  <Option value=\"AutoLostDecrease\">\r\n    <IsEnabled value=\"Fal" +
            "se\" />\r\n  </Option>\r\n  <Option value=\"PrinceHorse\">\r\n    <IsEnabled value=\"False" +
            "\" />\r\n  </Option>\r\n  <Option value=\"PrincePegasus\">\r\n    <IsEnabled value=\"False" +
            "\" />\r\n  </Option>\r\n  <Option value=\"PrinceCoin\">\r\n    <IsEnabled value=\"False\" /" +
            ">\r\n  </Option>\r\n  <Option value=\"PrinceFood\">\r\n    <IsEnabled value=\"False\" />\r\n" +
            "  </Option>\r\n  <Option value=\"RandomParty10\">\r\n    <IsEnabled value=\"False\" />\r\n" +
            "  </Option>\r\n  <Option value=\"RandomParty08\">\r\n    <IsEnabled value=\"False\" />\r\n" +
            "  </Option>\r\n  <Option value=\"RandomParty05\">\r\n    <IsEnabled value=\"False\" />\r\n" +
            "  </Option>\r\n  <Option value=\"RandomParty03\">\r\n    <IsEnabled value=\"False\" />\r\n" +
            "  </Option>\r\n  <Option value=\"RandomParty01\">\r\n    <IsEnabled value=\"False\" />\r\n" +
            "  </Option>\r\n  <Option value=\"PartyCustom\">\r\n    <IsEnabled value=\"False\" />\r\n  " +
            "</Option>\r\n  <Option value=\"Dwarf\">\r\n    <IsEnabled value=\"False\" />\r\n  </Option" +
            ">\r\n  <Option value=\"Eagle\">\r\n    <IsEnabled value=\"False\" />\r\n  </Option>\r\n  <Op" +
            "tion value=\"Elf\">\r\n    <IsEnabled value=\"False\" />\r\n  </Option>\r\n  <Option value" +
            "=\"Falcon\">\r\n    <IsEnabled value=\"False\" />\r\n  </Option>\r\n  <Option value=\"Griff" +
            "on\">\r\n    <IsEnabled value=\"False\" />\r\n  </Option>\r\n  <Option value=\"Harpy\">\r\n  " +
            "  <IsEnabled value=\"False\" />\r\n  </Option>\r\n  <Option value=\"Magician\">\r\n    <Is" +
            "Enabled value=\"False\" />\r\n  </Option>\r\n  <Option value=\"Mercenary\">\r\n    <IsEnab" +
            "led value=\"False\" />\r\n  </Option>\r\n  <Option value=\"Merchant\">\r\n    <IsEnabled v" +
            "alue=\"False\" />\r\n  </Option>\r\n  <Option value=\"Minstrel\">\r\n    <IsEnabled value=" +
            "\"False\" />\r\n  </Option>\r\n  <Option value=\"Monk\">\r\n    <IsEnabled value=\"False\" /" +
            ">\r\n  </Option>\r\n  <Option value=\"PorterSlave\">\r\n    <IsEnabled value=\"False\" />\r" +
            "\n  </Option>\r\n  <Option value=\"TrueLove\">\r\n    <IsEnabled value=\"False\" />\r\n  </" +
            "Option>\r\n  <Option value=\"Wizard\">\r\n    <IsEnabled value=\"False\" />\r\n  </Option>" +
            "\r\n  <Option value=\"PartyMounted\">\r\n    <IsEnabled value=\"False\" />\r\n  </Option>\r" +
            "\n  <Option value=\"PartyAirborne\">\r\n    <IsEnabled value=\"False\" />\r\n  </Option>\r" +
            "\n  <Option value=\"RandomHex\">\r\n    <IsEnabled value=\"False\" />\r\n  </Option>\r\n  <" +
            "Option value=\"RandomTown\">\r\n    <IsEnabled value=\"False\" />\r\n  </Option>\r\n  <Opt" +
            "ion value=\"RandomLeft\">\r\n    <IsEnabled value=\"False\" />\r\n  </Option>\r\n  <Option" +
            " value=\"RandomRight\">\r\n    <IsEnabled value=\"False\" />\r\n  </Option>\r\n  <Option v" +
            "alue=\"RandomBottom\">\r\n    <IsEnabled value=\"False\" />\r\n  </Option>\r\n  <Option va" +
            "lue=\"0109\">\r\n    <IsEnabled value=\"False\" />\r\n  </Option>\r\n  <Option value=\"0206" +
            "\">\r\n    <IsEnabled value=\"False\" />\r\n  </Option>\r\n  <Option value=\"0711\">\r\n    <" +
            "IsEnabled value=\"False\" />\r\n  </Option>\r\n  <Option value=\"1212\">\r\n    <IsEnabled" +
            " value=\"False\" />\r\n  </Option>\r\n  <Option value=\"0323\">\r\n    <IsEnabled value=\"F" +
            "alse\" />\r\n  </Option>\r\n  <Option value=\"1923\">\r\n    <IsEnabled value=\"False\" />\r" +
            "\n  </Option>\r\n  <Option value=\"0418\">\r\n    <IsEnabled value=\"False\" />\r\n  </Opti" +
            "on>\r\n  <Option value=\"0722\">\r\n    <IsEnabled value=\"False\" />\r\n  </Option>\r\n  <O" +
            "ption value=\"0409\">\r\n    <IsEnabled value=\"False\" />\r\n  </Option>\r\n  <Option val" +
            "ue=\"0406\">\r\n    <IsEnabled value=\"False\" />\r\n  </Option>\r\n  <Option value=\"0405\"" +
            ">\r\n    <IsEnabled value=\"False\" />\r\n  </Option>\r\n  <Option value=\"0411\">\r\n    <I" +
            "sEnabled value=\"False\" />\r\n  </Option>\r\n  <Option value=\"0407\">\r\n    <IsEnabled " +
            "value=\"False\" />\r\n  </Option>\r\n  <Option value=\"1905\">\r\n    <IsEnabled value=\"Fa" +
            "lse\" />\r\n  </Option>\r\n  <Option value=\"1723\">\r\n    <IsEnabled value=\"False\" />\r\n" +
            "  </Option>\r\n  <Option value=\"LessHardMonsters\">\r\n    <IsEnabled value=\"False\" /" +
            ">\r\n  </Option>\r\n  <Option value=\"EasyMonsters\">\r\n    <IsEnabled value=\"False\" />" +
            "\r\n  </Option>\r\n  <Option value=\"EasiestMonsters\">\r\n    <IsEnabled value=\"False\" " +
            "/>\r\n  </Option>\r\n  <Option value=\"NoLostRoll\">\r\n    <IsEnabled value=\"False\" />\r" +
            "\n  </Option>\r\n  <Option value=\"ForceNoLostEvent\">\r\n    <IsEnabled value=\"False\" " +
            "/>\r\n  </Option>\r\n  <Option value=\"ForceNoEvent\">\r\n    <IsEnabled value=\"False\" /" +
            ">\r\n  </Option>\r\n  <Option value=\"ForceNoRoadEvent\">\r\n    <IsEnabled value=\"False" +
            "\" />\r\n  </Option>\r\n  <Option value=\"ForceNoCrossEvent\">\r\n    <IsEnabled value=\"F" +
            "alse\" />\r\n  </Option>\r\n  <Option value=\"ForceNoRaftEvent\">\r\n    <IsEnabled value" +
            "=\"False\" />\r\n  </Option>\r\n  <Option value=\"ForceNoAirEvent\">\r\n    <IsEnabled val" +
            "ue=\"False\" />\r\n  </Option>\r\n  <Option value=\"ForceLostEvent\">\r\n    <IsEnabled va" +
            "lue=\"False\" />\r\n  </Option>\r\n  <Option value=\"ForceLostAfterCrossEvent\">\r\n    <I" +
            "sEnabled value=\"False\" />\r\n  </Option>\r\n  <Option value=\"ForceEvent\">\r\n    <IsEn" +
            "abled value=\"False\" />\r\n  </Option>\r\n  <Option value=\"ForceCrossEvent\">\r\n    <Is" +
            "Enabled value=\"False\" />\r\n  </Option>\r\n  <Option value=\"ForceRaftEvent\">\r\n    <I" +
            "sEnabled value=\"False\" />\r\n  </Option>\r\n  <Option value=\"ForceAirEvent\">\r\n    <I" +
            "sEnabled value=\"False\" />\r\n  </Option>\r\n</Options>\"")]
        public string GameOptions {
            get {
                return ((string)(this["GameOptions"]));
            }
            set {
                this["GameOptions"] = value;
            }
        }
    }
}
